[profile.default]
src = "src"
out = "out"
libs = ["lib"]

is-system = true

via_ir = true

optimizer = true
optimizer_runs = 200

remappings = [
    '@openzeppelin=lib/openzeppelin-contracts/',
    '@foundry-era-contracts=lib/foundry-era-contracts/src',
    '@account-abstraction=lib/account-abstraction/',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
